yntax on
set number
set tabstop=4
set softtabstop=4
set shiftwidth=4
set textwidth=100
set expandtab
set autoindent
set fileformat=unix
set enc=utf-8
set fenc=utf-8
set termencoding=utf-8
set showmatch
